[book]
authors = ["Luca Donno"]
language = "en"
src = "src"
title = "Native rollups"

[output.html]
additional-js = ["static/solidity.min.js", "static/external-links.js"]
default-theme = "ayu"

[output.html.redirect]
"/execute_precompile.html" = "specification.html"
"/proof_carrying_transactions.html" = "specification.html"
"/stacks_review.html" = "orbit_stack.html"
"/native_verification.html" = "generalized_proof_verification.html"
"/proofs.html" = "generalized_proof_verification.html"
"/l1_anchoring.html" = "messaging.html"
"/l1_l2_messaging.html" = "messaging.html"
"/l2_l1_messaging.html" = "messaging.html"
